---
- name: Add team access
  ansible.builtin.command: >
    awx-manage shell_plus --command="from awx.main.models import Credential, Team;
    cred = Credential.objects.get(id={{ new_cred.stdout }});
    team = Team.objects.get(id={{ access_list_item.id }});
    cred.{{ access_list_item.role }}_role.team_set.add(team)"
  delegate_to: "{{ awx_controller }}" # added this line
  become: true # added become: true to allow privilege escalation for awx-manage
  changed_when: true
