---
- name: Import Credentials into Ansible Automation Platform
  hosts: localhost
  gather_facts: false
  become: false  # We'll use awx-manage, which handles privileges.
  vars:
    credential_file: ""  # Placeholder, must be defined when calling.
    duplicates: []
    imported_count: 0

  tasks:
    - name: Check if credential file exists
      ansible.builtin.stat:
        path: "{{ credential_file }}"
      register: file_check
      failed_when: not file_check.stat.exists

    - name: Read credentials from JSON file
      ansible.builtin.slurp:
        src: "{{ credential_file }}"
      register: creds_json_content

    - name: Parse JSON content
      ansible.builtin.set_fact:
        creds_data: "{{ creds_json_content.content | b64decode | from_json }}"

    - name: Import credentials iteratively
      ansible.builtin.include_tasks: import_single_credential.yml
      loop: "{{ creds_data }}"
      loop_control:
        loop_var: cred_data

    - name: Report Import Summary
      ansible.builtin.debug:
        msg:
          - "Imported {{ imported_count }} credentials."
          - "Skipped (duplicates): {{ duplicates }}"
      when: duplicates|length > 0

    - name: Report successful import
      ansible.builtin.debug:
        msg: "Imported {{ imported_count }} credentials."
      when: duplicates|length == 0
