---
- name: Associate job template
  ansible.builtin.command: >
    awx-manage shell_plus --command="from awx.main.models import Credential, JobTemplate;
    cred = Credential.objects.get(id={{ new_cred.stdout }});
    jt = JobTemplate.objects.get(id={{ jt_data.id }});
    jt.credentials.add(cred)"
  delegate_to: "{{ awx_controller }}" # added this line
  become: true # added become: true to allow privilege escalation for awx-manage
  changed_when: true
