---
- name: Import All Credentials into Ansible Automation Platform (SSH)
  hosts: localhost  # Playbook runs on your workstation
  gather_facts: false
  become: false  # Not needed for the initial tasks
  vars:
    credential_file: ""  # Placeholder - MUST be defined.
    awx_controller: ""  # Hostname or IP of your AWX/AAP controller
    awx_ssh_user: "" #  SSH User
    duplicates: []
    imported_count: 0

  tasks:
    - name: Check if credential file exists (on local workstation)
      ansible.builtin.stat:
        path: "{{ credential_file }}"
      register: file_check
      failed_when: not file_check.stat.exists

    - name: Read credentials from JSON file (on local workstation)
      ansible.builtin.slurp:
        src: "{{ credential_file }}"
      register: creds_json_content

    - name: Parse JSON content
      ansible.builtin.set_fact:
        creds_data: "{{ creds_json_content.content | b64decode | from_json }}"

    - name: Iterate through credentials (delegated tasks)
      ansible.builtin.include_tasks: import_single_credential_ssh.yml
      loop: "{{ creds_data }}"
      loop_control:
        loop_var: cred_data

    - name: Report Import Summary
      ansible.builtin.debug:
        msg:
          - "Imported {{ imported_count }} credentials."
          - "Skipped (duplicates): {{ duplicates }}"
      when: duplicates | length > 0

    - name: Report successful import (no duplicates)
      ansible.builtin.debug:
        msg: "Imported {{ imported_count }} credentials."
      when: duplicates | length == 0
