---
- name: Add user access
  ansible.builtin.command: >
    awx-manage shell_plus --command="from awx.main.models import Credential, User;
    cred = Credential.objects.get(id={{ new_cred.stdout }});
    user = User.objects.get(id={{ access_list_item.id }});
    cred.{{ access_list_item.role }}_role.members.add(user)"
  delegate_to: "{{ awx_controller }}" # added this line
  become: true # added become: true to allow privilege escalation for awx-manage
  changed_when: true
